### ISSUE TITLE
[Bug]: 推理和转换ONNX时报错

### ISSUE THREAD

**Issue by m00nLi** [xiuqhou/Relation-DETR#24]
### Bug

训练正常，但是使用`inference.py`推理或者转换ONNX时报错： 
```
Traceback (most recent call last):
  File "/home/code/Relation-DETR/inference.py", line 165, in <module>
    inference()
  File "/home/user/code/Relation-DETR/inference.py", line 99, in inference
    model = Config(args.model_config).model.eval()
  File "/home/code/Relation-DETR/util/lazy_load.py", line 35, in __init__
    mod = importlib.import_module(module_name)
  File "/home/user/miniconda3/envs/detr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/code/Relation-DETR/configs/train_config.py", line 45, in <module>
    optimizer = optim.AdamW(lr=learning_rate, weight_decay=1e-4, betas=(0.9, 0.999))
TypeError: AdamW.__init__() missing 1 required positional argument: 'params'
```

### 环境信息

```
-------------------------------  ---------------------------------------------------------------------------------------
sys.platform                     linux
Python                           3.10.14 | packaged by conda-forge | (main, Mar 20 2024, 12:45:18) [GCC 12.3.0]
numpy                            1.24.4
PyTorch                          2.4.0+cu121 @/home/user/miniconda3/envs/detr/lib/python3.10/site-packages/torch
PyTorch debug build              False
torch._C._GLIBCXX_USE_CXX11_ABI  False
GPU available                    Yes
GPU 0,1,2,3,4,5,6,7              NVIDIA H800 (arch=9.0)
Driver version                   560.35.03
CUDA_HOME                        /usr/local/cuda-12.4
Pillow                           10.4.0
torchvision                      0.19.0+cu121 @/home/user/miniconda3/envs/detr/lib/python3.10/site-packages/torchvision
torchvision arch flags           5.0, 6.0, 7.0, 7.5, 8.0, 8.6, 9.0
fvcore                           0.1.5.post20221221
iopath                           0.1.10
cv2                              4.10.0
-------------------------------  ---------------------------------------------------------------------------------------
```

**Comment by xiuqhou** [comment]
model_config应该指定的是模型配置而不是训练配置，例如：
configs/relation_detr/relation_detr_resnet50_800_1333.py

**Comment by m00nLi** [comment]
> model_config应该指定的是模型配置而不是训练配置，例如： configs/relation_detr/relation_detr_resnet50_800_1333.py

好的，换成模型配置没问题了

**Comment by m00nLi** [comment]
导出ONNX时报错：
```
torch.onnx.errors.UnsupportedOperatorError: Exporting the operator 'aten::_upsample_bilinear2d_aa' to ONNX opset version 17 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub: https://github.com/pytorch/pytorch/issues.
```
ONNX版本
```
onnx                              1.16.2
onnxruntime                       1.16.0
onnxsim                           0.4.36
rapidocr-onnxruntime              1.3.24
```

**Comment by xiuqhou** [comment]
Hi @m00nLi 这是因为pytorch不支持抗锯齿resize导出ONNX，
请把models/detectors/base_detector.py第75行的antialias设置为False再导出

**Comment by SEU-ZWW** [comment]
> Hi @m00nLi 这是因为pytorch不支持抗锯齿resize导出ONNX， 请把models/detectors/base_detector.py第75行的antialias设置为False再导出

设置为False后还是会报同样的错，opset 11也不行

**Comment by xiuqhou** [comment]
请看一下报的错误是`aten::_upsample_bilinear2d_aa`还是`aten::_upsample_bilinear2d`。带`_aa`版本的算子目前pytorch都不支持，而设置为False使用的是不带`_aa`版本的ONNX算子，这个算子可能在opset 11不支持，但在opset 17是支持的，请试试opset 17可以吗？

**Comment by SEU-ZWW** [comment]
> 请看一下报的错误是`aten::_upsample_bilinear2d_aa`还是`aten::_upsample_bilinear2d`。带`_aa`版本的算子目前pytorch都不支持，而设置为False使用的是不带`_aa`版本的ONNX算子，这个算子可能在opset 11不支持，但在opset 17是支持的，请试试opset 17可以吗？
报错的是带_aa的算子，那请问作者目前有什么办法可以把pt转成onnx么，麻烦给个解决方案吧，谢谢

**Comment by xiuqhou** [comment]
Hi @SEU-ZWW 如果报错的是带`_aa`的算子，说明antialias还是True。麻烦检查一下参数设置，可以调试看看为什么antialias设置为False没有生效。

**Comment by m00nLi** [comment]
我的转ONNX成功了，antialias=False, opset=17， onnxruntime==1.19.2.
请问下用onnx检测的时候需要对图片进行什么预处理吗？我看了下`tools/pytorch2onnx.py` 的`ONNXDetector`,
我这样预处理输入图片是有检测结果的：
```
cv_img = cv2.imread(image_path)
cv_img = cv2.cvtColor(cv_img, cv2.COLOR_BGR2RGB)
cv_img = cv_img.astype(np.float32)
cv_img /= 255.0
mean=(0.485, 0.456, 0.406),
std=(0.229, 0.224, 0.225)
# cv_img = (cv_img - mean) / std  # 加上这行没有检测结果
cv_img = cv_img.transpose(2, 0, 1)  # h, w, c => c, h, w
input_tensor = torch.from_numpy(cv_img)
result = onnx_detector.__call__([input_tensor])
```
但我看了训练时的数据处理，不是还有一步减均值除方差吗？但是加上的话就检测不到目标了，所以正确的预处理该怎么写？

**Comment by xiuqhou** [comment]
为了方便使用，我把推理时候的归一化作为nn.Module集成到模型中了，所以推理不需要再做额外的归一化，只需要读取chw(rgb通道)格式的图片，转成浮点数格式输入模型就可以了，您原本的预处理就是对的

**Comment by m00nLi** [comment]
> 为了方便使用，我把推理时候的归一化作为nn.Module集成到模型中了，所以推理不需要再做额外的归一化，只需要读取chw(rgb通道)格式的图片，转成浮点数格式输入模型就可以了，您原本的预处理就是对的

好的谢谢

**Comment by m00nLi** [comment]
> 为了方便使用，我把推理时候的归一化作为nn.Module集成到模型中了，所以推理不需要再做额外的归一化，只需要读取chw(rgb通道)格式的图片，转成浮点数格式输入模型就可以了，您原本的预处理就是对的

请问下导出ONNX时如何去掉这个缩放+归一化的算子？我已经在`models/detectors/base_detector.py`将`self.eval_transform=None`了，用Netron看应该是去掉那个算子了，但是图片的预处理还是像之前那样才有检测结果（自己做归一化没有检测结果）。
```
class BaseDetector(nn.Module):
    def __init__(self, min_size=None, max_size=None, size_divisible=32):
        ...
       # self.eval_transform = nn.Sequential(*eval_transform)
       self.eval_transform = None
```
另外，在我的个人数据集（约20万）上测试，ReleationDETR(FocalNet-L)的mAP50, mAP50-95这些的确比DINO(Swin-L)高出3个百分点，Recall也高3个点，但是Precision却低了7个点，意味着ReleationDETR模型偏向于查全率，但误检会很多，这个有什么改进思路吗？

**Comment by xiuqhou** [comment]
很奇怪，eval_transform只是对图片进行float+归一化操作，把它设置为None就不会再进行归一化了。您可以调试pytorch2onnx.py文件中的torch.onnx.export函数，看看在导出时是否真的把归一化去掉了，另外也要注意图片类型必须是float。

检测需要同时考虑分类和回归任务，所以主要是用mAP和AR来衡量性能。AP的定义是不同召回率水平下Precision的平均值，即PR曲线下方的面积，mAP是每个类别AP的平均值。所以我不太明白为什么Precision跟mAP的趋势不同，mAP比DINO高但Precision比DINO低，这是很奇怪的一件事，建议先可视化看看结果是否真的存在很多误检。如果存在很多误检的话，可以设置阈值来过滤掉一部分结果，或者对物体query进行优化，更精确地表示物体。

**Comment by Bin-ze** [comment]
我使用pytorch2onnx.py导出onnx模型:
> python tools/pytorch2onnx.py --model-config configs/relation_detr/relati
on_detr_swin_l_800_1333.py --checkpoint ckpts/relation_detr_swin_l_800_1333_coco_2x.pth --save-file relation_detr.onnx --simplify --verify

并尝试使用ONNXDetector推理自己的图像，我的图像来自cam:


    '''python
    detector = ONNXDetector(
          onnx_file="/home/guozebin/workspace/Deploy/detection/Relation-DETR/relation_detr.onnx",
      )
    for v in video_caps:
        ret, frame = v.read()
        frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
        images = torch.tensor(frame.transpose(2, 0, 1), dtype=torch.float32)[None]
        res = detector(images)
    '''

我发现得到的检测结果与未导出的pth模型相比的置信度非常低，且基本都是错误的
我想知道你们遇到这样的问题没有，又该如何解决呢？

**Comment by xiuqhou** [comment]
@Bin-ze 请问导出的时候onnx模型和pytorch模型在verify后的结果差异大吗？

**Comment by Bin-ze** [comment]
这是完整的导出日志：

```shell
python tools/pytorch2onnx.py --model-config configs/relation_detr/relation_detr_swin_l_800_1333.py --checkpoint ckpts/relation_detr_swin_l_800_1333_coco_2x.pth --save-file relation_detr.onnx --simplify --verify 

Using /home/guozebin/.cache/torch_extensions/py310_cu124 as PyTorch extensions root...
Detected CUDA files, patching ldflags
Emitting ninja build file /home/guozebin/.cache/torch_extensions/py310_cu124/MultiScaleDeformableAttention/build.ninja...
/home/guozebin/miniconda3/envs/monitor_v1/lib/python3.10/site-packages/torch/utils/cpp_extension.py:1964: UserWarning: TORCH_CUDA_ARCH_LIST is not set, all archs for visible cards are included for compilation. 
If this is not desired, please set os.environ['TORCH_CUDA_ARCH_LIST'].
  warnings.warn(
Building extension module MultiScaleDeformableAttention...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
Loading extension module MultiScaleDeformableAttention...
The model and loaded state dict do not match exactly
Size mismatch keys: head.weight, head.bias
+-------------+----------------+---------------------+
| key name    | shape in model | shape in state dict |
+-------------+----------------+---------------------+
| head.weight | (1000, 1536)   | (21841, 1536)       |
+-------------+----------------+---------------------+
| head.bias   | (1000,)        | (21841,)            |
+-------------+----------------+---------------------+

/home/guozebin/workspace/Deploy/detection/Relation-DETR/tools/pytorch2onnx.py:82: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  checkpoint = torch.load(args.checkpoint, map_location="cpu")
/home/guozebin/workspace/Deploy/detection/Relation-DETR/models/detectors/base_detector.py:41: TracerWarning: Iterating over a tensor might cause the trace to be incorrect. Passing a tensor of different shape won't change the number of iterations executed (and might lead to errors or silently give incorrect results).
  orig_height, orig_width = operators.shape_as_tensor(image)[-2:]
/home/guozebin/workspace/Deploy/detection/Relation-DETR/transforms/v2/functional/_misc.py:34: TracerWarning: torch.as_tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  mean = torch.as_tensor(mean, dtype=dtype, device=device)
/home/guozebin/workspace/Deploy/detection/Relation-DETR/transforms/v2/functional/_misc.py:35: TracerWarning: torch.as_tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  std = torch.as_tensor(std, dtype=dtype, device=device)
/home/guozebin/workspace/Deploy/detection/Relation-DETR/util/misc.py:81: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert all(
/home/guozebin/workspace/Deploy/detection/Relation-DETR/models/backbones/swin.py:142: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if window_size[0] >= pad_H:
/home/guozebin/workspace/Deploy/detection/Relation-DETR/models/backbones/swin.py:144: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if window_size[1] >= pad_W:
/home/guozebin/workspace/Deploy/detection/Relation-DETR/models/bricks/base_transformer.py:96: TracerWarning: Iterating over a tensor might cause the trace to be incorrect. Passing a tensor of different shape won't change the number of iterations executed (and might lead to errors or silently give incorrect results).
  p + l.view(1, -1, 1, 1) for p, l in zip(multi_level_pos_embeds, self.level_embeds)
/home/guozebin/workspace/Deploy/detection/Relation-DETR/models/bricks/base_transformer.py:44: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if h == 0 or w == 0:  # for empty Tensor
/home/guozebin/workspace/Deploy/detection/Relation-DETR/models/bricks/base_transformer.py:59: TracerWarning: Iterating over a tensor might cause the trace to be incorrect. Passing a tensor of different shape won't change the number of iterations executed (and might lead to errors or silently give incorrect results).
  for lvl, (h, w) in enumerate(spatial_shapes):
/home/guozebin/workspace/Deploy/detection/Relation-DETR/models/bricks/ms_deform_attn.py:313: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert (spatial_shapes[:, 0] * spatial_shapes[:, 1]).sum() == num_value
/home/guozebin/workspace/Deploy/detection/Relation-DETR/models/bricks/ms_deform_attn.py:339: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if reference_points.shape[-1] == 2:
/home/guozebin/workspace/Deploy/detection/Relation-DETR/models/bricks/ms_deform_attn.py:106: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert n == gn
/home/guozebin/workspace/Deploy/detection/Relation-DETR/models/bricks/ms_deform_attn.py:345: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  elif reference_points.shape[-1] == 4:
/home/guozebin/miniconda3/envs/monitor_v1/lib/python3.10/site-packages/torch/__init__.py:2040: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert condition, message
/home/guozebin/workspace/Deploy/detection/Relation-DETR/models/detectors/base_detector.py:175: TracerWarning: Iterating over a tensor might cause the trace to be incorrect. Passing a tensor of different shape won't change the number of iterations executed (and might lead to errors or silently give incorrect results).
  } for a, b in zip(outputs_class[:-1], outputs_coord[:-1])]
/home/guozebin/workspace/Deploy/detection/Relation-DETR/models/bricks/post_process.py:25: TracerWarning: Using len to get tensor shape might cause the trace to be incorrect. Recommended usage would be tensor.shape[0]. Passing a tensor of different shape might lead to errors or silently give incorrect results.
  assert len(out_logits) == len(target_sizes)
/home/guozebin/workspace/Deploy/detection/Relation-DETR/models/bricks/post_process.py:26: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert target_sizes.shape[1] == 2
/home/guozebin/miniconda3/envs/monitor_v1/lib/python3.10/site-packages/torch/onnx/_internal/jit_utils.py:308: UserWarning: Constant folding - Only steps=1 can be constant folded for opset >= 10 onnx::Slice op. Constant folding not applied. (Triggered internally at ../torch/csrc/jit/passes/onnx/constant_fold.cpp:178.)
  _C._jit_pass_onnx_node_shape_type_inference(node, params_dict, opset_version)
/home/guozebin/miniconda3/envs/monitor_v1/lib/python3.10/site-packages/torch/onnx/utils.py:663: UserWarning: Constant folding - Only steps=1 can be constant folded for opset >= 10 onnx::Slice op. Constant folding not applied. (Triggered internally at ../torch/csrc/jit/passes/onnx/constant_fold.cpp:178.)
  _C._jit_pass_onnx_graph_shape_type_inference(
/home/guozebin/miniconda3/envs/monitor_v1/lib/python3.10/site-packages/torch/onnx/utils.py:1186: UserWarning: Constant folding - Only steps=1 can be constant folded for opset >= 10 onnx::Slice op. Constant folding not applied. (Triggered internally at ../torch/csrc/jit/passes/onnx/constant_fold.cpp:178.)
  _C._jit_pass_onnx_graph_shape_type_inference(
Successfully simplified ONNX model: relation_detr.onnx
Successfully exported ONNX model: relation_detr.onnx
/home/guozebin/miniconda3/envs/monitor_v1/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py:115: UserWarning: Specified provider 'CUDAExecutionProvider' is not in available provider names.Available providers: 'AzureExecutionProvider, CPUExecutionProvider'
  warnings.warn(
Traceback (most recent call last):
  File "/home/guozebin/workspace/Deploy/detection/Relation-DETR/tools/pytorch2onnx.py", line 133, in <module>
    pytorch2onnx()
  File "/home/guozebin/workspace/Deploy/detection/Relation-DETR/tools/pytorch2onnx.py", line 128, in pytorch2onnx
    np.testing.assert_allclose(onnx_res, pytorch_res, rtol=1e-3, atol=1e-5, err_msg=err_msg)
  File "/home/guozebin/miniconda3/envs/monitor_v1/lib/python3.10/site-packages/numpy/testing/_private/utils.py", line 1504, in assert_allclose
    assert_array_compare(compare, actual, desired, err_msg=str(err_msg),
  File "/home/guozebin/miniconda3/envs/monitor_v1/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/guozebin/miniconda3/envs/monitor_v1/lib/python3.10/site-packages/numpy/testing/_private/utils.py", line 797, in assert_array_compare
    raise AssertionError(msg)

AssertionError: 
Not equal to tolerance rtol=0.001, atol=1e-05
The numerical values are different between Pytorch and ONNXBut it does not necessarily mean the exported ONNX is problematic.
Mismatched elements: 13 / 1200 (1.08%)
Max absolute difference: 0.01086426
Max relative difference: 0.0020979
 x: array([[4.558563e-02, 3.453702e+00, 7.992456e+02, 1.315864e+03],
       [4.558563e-02, 3.453702e+00, 7.992456e+02, 1.315864e+03],
       [4.558563e-02, 3.453702e+00, 7.992456e+02, 1.315864e+03],...
 y: array([[4.558563e-02, 3.453782e+00, 7.992456e+02, 1.315864e+03],
       [4.558563e-02, 3.453782e+00, 7.992456e+02, 1.315864e+03],
       [4.558563e-02, 3.453782e+00, 7.992456e+02, 1.315864e+03],...


```

从结果上看，差异并不大，但是大于设置的阈值

除此之外，我发现该脚本无法导出relation_detr_focalnet_large_lrf_fl4_1200_2000_o365_4e-coco_2x.pth,在导出过程中，该进程将占用我的120G本地服务器内存，然后进程被杀死

请问您遇到这样的情况了吗，有应该如何解决，期待您的回复
@xiuqhou

**Comment by Bin-ze** [comment]
补充说明：  
   我希望导出更大的模型，因为在我的测试中，使用resnet50以及使用swin和focalnet的模型在对较差镜头的检测结果上的差距是断层式的，resnet50在我的场景基本不可用。
   但是正如上述导出的情况，swin模型的head部分似乎在权重中有更多的query，但是我在pth模型上测试发现，这个权重不匹配似乎并不影响检测结果，但导出的onnx不可用，而且我还想继续将其量化为tensort支持的engine用于进一步加速，我想知道我该怎样做。
对于focalnet，将会沾满我的整个内存，进程直接中断

除此之外，我想了解onnx或者engine相对于原生的pytorch在该模型上的提速是怎样的，我并没有在paper和readme中看到对应的对比，如果您有做过相关实验，能否告知，非常期待您的回复

**Comment by xiuqhou** [comment]
@Bin-ze 从日志来看导出是没问题的，误差在合理的范围内。那么问题应该是后续ONNX模型的调用有错误，您可以检查下后续的调用方式和导出脚本中的调用方式是否一致？或者麻烦提供下完整的ONNX推理代码。

如果想将ONNX转为TensorRT支持的engine，可以用TensorRT提供的trtexec脚本，网上有很多资料可参考。

对于导出大模型占用太多显存的问题，抱歉我无法提供太多帮助，提供的导出脚本只是调用了`torch.onnx.export`函数，占用太多内存的问题可能和函数设置有关，建议去`pytorch`仓库反馈这个问题

**Comment by Bin-ze** [comment]
这是完整的脚本，看不出哪里存在问题：

```
import onnx

from typing import List, Union, Dict, Tuple
import torch
import warnings
import numpy as np

import torchvision
from ultralytics.engine.results import Results

class ONNXDetector:
    def __init__(self, onnx_file: str, thresh: float = 0.6,):
        import onnxruntime
        self.session = onnxruntime.InferenceSession(
            onnx_file, providers=["CUDAExecutionProvider", "CPUExecutionProvider"]
        )
        self.io_binding = self.session.io_binding()
        self.is_cuda_available = onnxruntime.get_device() == "GPU"
        self.person_label = 0
        self.thresh = thresh
        
    def __call__(self, frames: List[np.ndarray]):
        
        results = []
        for idx, frame in enumerate(frames):  # bs=1 needs 8G memory
            print(f"handle cam {idx}")
            images = torch.tensor(frame.transpose(2, 0, 1), dtype=torch.float32)[None].cuda()
            # set io binding for inputs/outputs
            device_type = images.device.type if self.is_cuda_available else "cpu"
            if not self.is_cuda_available:
                images = images.cpu()
            self.io_binding.bind_input(
                name="images",
                device_type=device_type,
                device_id=0,
                element_type=np.float32,
                shape=images.shape,
                buffer_ptr=images.data_ptr(),
            )
            for output in self.session.get_outputs():
                self.io_binding.bind_output(output.name)

            # run session to get outputs
            self.session.run_with_iobinding(self.io_binding)
            prediction = self.io_binding.copy_outputs_to_cpu()
            # print(prediction[0])
            # 筛选出标签为person的检测结果
            person_indices = [i for i, label in enumerate(prediction[1]) if label == self.person_label]
            person_boxes = prediction[2][person_indices]
            person_scores = prediction[0][person_indices]
            person_labels = prediction[1][person_indices]
            print(person_scores)

if __name__ == "__main__":
    import cv2
    
    detector = ONNXDetector(
        onnx_file="~/workspace/Deploy/detection/Relation-DETR/relation_detr.onnx",
    )

    video_caps = []
    for i in range(8):
        video_caps.append(cv2.VideoCapture(f'cam{i}.mp4'))

    k = 0
    fourcc = cv2.VideoWriter_fourcc(*'mp4v')
    videoWrite = None  # 动态初始化

    while True:
        frames = []
        for v in video_caps:
            ret, frame = v.read()
            if not ret:
                print("End of video or failed to read frame.")
                break
            frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
            frames.append(frame)
        results = detector(frames)
        img_h, img_w = results[0].plot().shape[:2]
        merged_array = np.empty((img_h * 2, img_w * 4, 3), dtype=np.uint8)

        for i in range(2):
            for j in range(4):
                idx = i * 4 + j
                if idx >= len(results):
                    break
                img = results[idx].plot()
                if img.shape[0] != img_h or img.shape[1] != img_w:
                    img = cv2.resize(img, (img_w, img_h))
                merged_array[i * img_h:(i + 1) * img_h, j * img_w:(j + 1) * img_w] = img
        
        # 动态初始化 VideoWriter
        if videoWrite is None:
            videoWrite = cv2.VideoWriter('detr_1080-1.mp4', fourcc, 10, (merged_array.shape[1], merged_array.shape[0]))
        
        videoWrite.write(cv2.cvtColor(merged_array, cv2.COLOR_RGB2BGR))  # 写入视频帧

        k += 1
        if k == 2: 
            break

    # 确保释放资源
    if videoWrite is not None:
        videoWrite.release()
        print("VideoWriter released.")


```

**Comment by Bin-ze** [comment]
这是我写的一个简化版本：

```python

import onnx

from typing import List, Union, Dict, Tuple
import torch
import warnings
import numpy as np
from torch import Tensor
import torchvision
from ultralytics.engine.results import Results

class ONNXDetector:
    def __init__(self, onnx_file):
        import onnxruntime
        self.session = onnxruntime.InferenceSession(
            onnx_file, providers=["CUDAExecutionProvider", "CPUExecutionProvider"]
        )
        self.io_binding = self.session.io_binding()
        self.is_cuda_available = onnxruntime.get_device() == "GPU"

    def __call__(self, images: List[Tensor], targets: List[Dict] = None):
        if targets is not None:
            warnings.warn("Currently ONNXDetector only support inference, targets will be ignored")
        assert len(images) == 1, "Currently ONNXDetector only support batch_size=1 for inference"
        assert images[0].ndim == 3, "Each image must be with three dimensions of C, H, W"
        if isinstance(images, (List, Tuple)):
            images = torch.stack(images)

        # set io binding for inputs/outputs
        device_type = images.device.type if self.is_cuda_available else "cpu"
        if not self.is_cuda_available:
            images = images.cpu()
        self.io_binding.bind_input(
            name="images",
            device_type=device_type,
            device_id=0,
            element_type=np.float32,
            shape=images.shape,
            buffer_ptr=images.data_ptr(),
        )
        for output in self.session.get_outputs():
            self.io_binding.bind_output(output.name)

        # run session to get outputs
        self.session.run_with_iobinding(self.io_binding)
        detections = self.io_binding.copy_outputs_to_cpu()
        return detections

if __name__ == "__main__":
    import cv2
    
    detector = ONNXDetector(
        onnx_file="~/workspace/Deploy/detection/Relation-DETR/relation_detr.onnx",
    )
    video_caps = cv2.VideoCapture(f'cam0.mp4')

    k = 0
    fourcc = cv2.VideoWriter_fourcc(*'mp4v')
    videoWrite = None  # 动态初始化

    while True:
        ret, frame = video_caps.read()
        if not ret:
            print("End of video or failed to read frame.")
            break
        frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
        images = torch.tensor(frame.transpose(2, 0, 1), dtype=torch.float32)
        results = detector([images])

```


从相同照片的推理结果上看，置信度跟导出前相比差异巨大

* pth推理：

<img width="1661" alt="Image" src="https://github.com/user-attachments/assets/9ce2fc09-ade4-45e9-b6fa-bab99da2966a" />

* onnx推理：

<img width="1672" alt="Image" src="https://github.com/user-attachments/assets/3886ba86-190a-4081-8062-a1bbe8599ee2" />


这是我导出的onnx的网址： [onnx weights](https://drive.google.com/file/d/1RhzNk_7figyahXDhvszoyp3jqxtUcTBZ/view?usp=drive_link)

您可以帮我进行测试吗？

**Comment by xiuqhou** [comment]
![Image](https://github.com/user-attachments/assets/2d38eb8a-161b-40ed-9378-96a032c50ebc)

@Bin-ze 我自己导出swin-l模型并测试了结果，发现ONNX和pytorch模型的结果是一致的，没有遇到你说的问题。我手头上没有合适的视频做测试，所以在一张随机初始化的图片上测试的，这是代码。

```python
import warnings
from typing import Dict, List, Tuple

import numpy as np
import torch
from torch import Tensor


class ONNXDetector:
    def __init__(self, onnx_file):
        import onnxruntime

        self.session = onnxruntime.InferenceSession(
            onnx_file, providers=["CUDAExecutionProvider", "CPUExecutionProvider"]
        )
        self.io_binding = self.session.io_binding()
        self.is_cuda_available = onnxruntime.get_device() == "GPU"

    def __call__(self, images: List[Tensor], targets: List[Dict] = None):
        if targets is not None:
            warnings.warn(
                "Currently ONNXDetector only support inference, targets will be ignored"
            )
        assert len(images) == 1, (
            "Currently ONNXDetector only support batch_size=1 for inference"
        )
        assert images[0].ndim == 3, (
            "Each image must be with three dimensions of C, H, W"
        )
        if isinstance(images, (List, Tuple)):
            images = torch.stack(images)

        # set io binding for inputs/outputs
        device_type = images.device.type if self.is_cuda_available else "cpu"
        if not self.is_cuda_available:
            images = images.cpu()
        self.io_binding.bind_input(
            name="images",
            device_type=device_type,
            device_id=0,
            element_type=np.float32,
            shape=images.shape,
            buffer_ptr=images.data_ptr(),
        )
        for output in self.session.get_outputs():
            self.io_binding.bind_output(output.name)

        # run session to get outputs
        self.session.run_with_iobinding(self.io_binding)
        detections = self.io_binding.copy_outputs_to_cpu()
        return detections


if __name__ == "__main__":
    import cv2

    detector = ONNXDetector(
        onnx_file="relation_detr_swin_l.onnx",
    )
    image = torch.randn(1, 3, 800, 1333)
    result1 = detector(image)
    from configs.relation_detr.relation_detr_swin_l_800_1333 import model
    model.eval()
    model.load_state_dict(torch.load("relation_detr_swin_l_800_1333_coco_1x.pth"), strict=False)
    result2 = model(image)
    print(result1)
    print(result2)
```

你提供的ONNX权重有权限限制，我无法访问，如果方便的话可以发到我邮箱：xiuqhou@stu.xjtu.edu.cn

**Comment by Bin-ze** [comment]
我已经开通了权限，其次，可以使用有目标的图片测试吗？我随机初始化图像得到的结果看上去也是一致的，但是当推理正常的照片将得到错误的结果

**Comment by xiuqhou** [comment]
@Bin-ze 抱歉回复的比较慢！我前段时间出差，实在抽不出来时间调试这个bug。

我后来发现这个问题是因为推理方式不对，当我用上面回复的https://github.com/xiuqhou/Relation-DETR/issues/24#issuecomment-2671047585 推理代码图片时，ONNX runtime输出的结果会出现nan，导致两个输出的结果不一致：

![Image](https://github.com/user-attachments/assets/6b3f37e0-24cb-42f7-921e-28330d514e5f)

换成下面这种推理方式就没问题了：

```python

import cv2
import onnxruntime
import torch
import numpy as np

# prepare image
image = cv2.imread("data/coco/val2017/000000000139.jpg")
image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
image = image.transpose(2, 0, 1)[None]  # B, C, H, W
torch_image = torch.tensor(image)

# ONNXruntime inference
session = onnxruntime.InferenceSession(
    "relation_detr_swin_l.onnx",
    providers=["CUDAExecutionProvider", "CPUExecutionProvider"],
)


numpy_image = torch_image.numpy().astype(np.float32)
result1 = session.run(
    ["scores", "labels", "boxes"], {"images": numpy_image / 255.0}
)

# pytorch inference
from configs.relation_detr.relation_detr_swin_l_800_1333 import model
from util.utils import load_state_dict

model.eval()
load_state_dict(model, torch.load("relation_detr_swin_l_800_1333_coco_1x.pth"))
result2 = model(torch_image)

# check results
print(result1[0] - result2[0]["scores"].detach().numpy())
print(result1)
print(result2)

```

这是ONNX和pytorch模型的输出结果，可以看到两者基本是一致的：

![Image](https://github.com/user-attachments/assets/844b9f61-f913-4cd6-b1ec-6101fbf3b810)

![Image](https://github.com/user-attachments/assets/d7cdb279-4407-456f-b8ab-834325897f23)
